version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db_microservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_demo
    ports:
      - '5431:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  school:
    container_name: app_school
    build: .
    ports:
      - 8080:8080
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - DATABASE_URL=host.docker.internal:5431/db_microservices
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password_demo
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
